export const configFroalaEditor = {
  attribution: false,
  placeholderText: 'Nội dung...',
  imageUploadURL: `${import.meta.env.VITE_BASE_API_URL}v1/file/upload-image-froala`,
  imageCORSProxy: '',
  imageUpload: true,
  // Set request type.
  imageUploadMethod: 'POST',
  imageUploadParam: 'file',
  // Set max image size to 5MB.
  imageMaxSize: 5 * 1024 * 1024,
  // Allow to upload PNG and JPG.
  imageAllowedTypes: ['jpeg', 'jpg', 'png'],
  pluginsEnabled: [
    'table',
    'spell',
    'quote',
    'save',
    'quickInsert',
    'paragraphFormat',
    'paragraphStyle',
    'help',
    'draggable',
    'align',
    'link',
    'lists',
    'file',
    'image',
    'emoticons',
    'url',
    // 'video',
    'embedly',
    'colors',
    'entities',
    'inlineClass',
    'inlineStyle',
    'wordPaste',
    'track_changes',
    'specialCharacters',
    'spellChecker',
    'imageTUI',
    'markdown',
    'lineHeight',
    'lineBreaker',
    'imageManager',
    'fullscreen',
    'fontSize',
    'fontFamily',
    'fontAwesome',
    // 'filesManager',
    'codeView',
    'codeBeautifier',
    'charCounter',
  ],
};
